### ISSUE TITLE
Edit host and port

### ISSUE THREAD

**Issue by geftimov** [theappbusiness/android-proxy-toggle#13]
I installed the app and it was clear what I need to do to enable/disable the proxy.
However, my laptop IP is different than the defined one.

Should we change the design a little and change from TextView to EditText 
so we can allow the user to change the proxy host and port.

I was thinking to show edit option only if the proxy is disabled.
If I am missing something or this is not an issue please say.

**Comment by fmontesino** [comment]
Ah yes! I didn't expect anyone to use the app at this stage 😅 
As you probably saw in the demo last week, I have stashed changes with an EditText to be able to change it.

I was waiting until I have the final design from Flor to actually implement the UI, because I am lazy and I don't want to do it twice 😝 
Can send you the stashed changes if you want to test the app, or I will close this issue soon whenever I have the design!

**Comment by geftimov** [comment]
Maybe we can wait for the UI and close this issue after we implement it.
