### ISSUE TITLE
Will there be updates?

### ISSUE THREAD

**Issue by jbulies** [theappbusiness/android-proxy-toggle#32]
Hello, this application, this solution is very important to me. I have a question and suggestion.

Is it possible to add in future updates the ability to set username and password for the proxy?

On the other hand, is it possible to make the application system administrator so that permissions can be granted without having to connect to the PC and use the terminal?

Thanks

**Comment by geftimov** [comment]
This is a very simple tool that we’ve built to help ourselves and our testing team deal with setting proxies quicker.
Unfortunately, there’s no plan on expanding the functionality at this point since it’s perfect for our use cases, and we’re lacking time and availability at the moment.
We’re more than happy to accept pull requests!
